apis/urls.py
from django.urls import path
from .views import TaskListAPIView, TaskDetailAPIView, TaskGroupAPIView


urlpatterns = [
    path('groups/', TaskGroupAPIView.as_view(), name='group_list_api'),
    path('tasks/', TaskListAPIView.as_view(), name='task_list_api'),
    path('tasks/<uuid:pk>/', TaskDetailAPIView.as_view(), name='task_detail_api'),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path('not-admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('task/', include('todos.urls')),
    path('group/', include('groups.urls')),
    path('accounts/', include('allauth.urls')),
    path('custom_accounts/', include('accounts.urls')),
    path('api/', include('apis.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

groups/urls.py
from django.urls import path
from .views import (
    GroupListView, 
    GroupTaskListView, 
    GroupDeteleView, 
    GroupUpdateView,
    accept_invitation,
)

app_name = 'groups'

urlpatterns = [
    path('', GroupListView.as_view(), name='group_list'),
    path('<uuid:group_id>/tasks', GroupTaskListView.as_view(), name='group_task_list'),
    path('<uuid:group_id>/update', GroupUpdateView.as_view(), name='group_update'),
    path('<uuid:group_id>/delete', GroupDeteleView.as_view(), name='group_delete'),
    path('<uuid:token>/accept-invitation', accept_invitation, name='accept_invitation'),
]

todos/urls.py
from django.urls import path

from .views import (
    TaskListView,
    TaskDetailView,
    TaskUpdateView,
    TaskDeleteView,
    ToggleTaskCompletionView,
)

app_name = "tasks"

urlpatterns = [
    path('', TaskListView.as_view(), name='task_list'),
    path('<uuid:pk>/', TaskDetailView.as_view(), name='task_detail'),
    path('<uuid:pk>/update', TaskUpdateView.as_view(), name='task_update'),
    path('<uuid:pk>/detele', TaskDeleteView.as_view(), name='task_delete'),
    path('toggle-completion/<uuid:task_id>/', ToggleTaskCompletionView.as_view(), name='toggle_task_completion'),
]

todos/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

from groups.models import TaskGroup


class Task(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    group = models.ForeignKey(TaskGroup, on_delete=models.CASCADE, related_name='tasks', null=True, default=None)
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    completed = models.BooleanField(default=False, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("tasks:task_detail", args=[str(self.id)])
    

todos/forms.py
from django import forms
from .models import Task


class CreateTaskForm(forms.ModelForm):
    title = forms.CharField(
        label='',
        required=True,
        widget=forms.TextInput(attrs={'placeholder':'Add new task..'})
    )

    class Meta:
        model = Task
        fields = ['title']


class UpdateTaskForm(forms.ModelForm):
    completed = forms.BooleanField(
        label='Completed',
        required=False,
        widget=forms.CheckboxInput()
    )

    class Meta:
        model = Task
        fields = ['title', 'description', 'completed']
        

todos/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, UpdateView, DeleteView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.views import View
from django.shortcuts import get_object_or_404

from .models import Task
from .forms import UpdateTaskForm
from .mixins import TaskListViewMixin
    

class TaskListView(TaskListViewMixin, ListView):
    context_object_name = "tasks"
    
    def get_redirect_url(self):
        return reverse('tasks:task_list')
    

class ToggleTaskCompletionView(View):
    def post(self, request, task_id):
        task = get_object_or_404(Task, id=task_id)
        task.completed = not task.completed
        task.save()
        return JsonResponse({'success': True})


class TaskDetailView(LoginRequiredMixin, DetailView):
    model = Task
    template_name = "todos/task_detail.html"
    context_object_name = "task"


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    form_class = UpdateTaskForm
    template_name = "todos/task_update.html"

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)
    
    def get_object(self, queryset=None):
        return Task.objects.get(pk=self.kwargs['pk'])
    
    def get_success_url(self):
        return self.object.get_absolute_url()


class TaskDeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    template_name = "todos/task_confirm_delete.html"
    success_url = reverse_lazy('tasks:task_list')

templates/todos/task_confirm_delete.html
{% extends "_base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="d-flex flex-column align-items-center text-center">
        <h3>Are you sure you wanna delete task '{{ task.title }}'?</h3> 
        <div class="d-flex">  
        <form method="post">{% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-danger mx-2" type="submit">Confirm</button>
        </form>

        <a class="btn btn-secondary " href="{% url 'tasks:task_list' %}">Back to Tasks</a>
    </div></div> 
{% endblock %}

templates/todos/task_detail.html
{% extends "_base.html" %}

{% block content %}
    <div class="d-flex flex-column">
        <a class="icon-link icon-link-hover link-body-emphasis" href="{% url 'tasks:task_list' %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8"/>
            </svg>
            Back to Tasks
        </a>

        <h3>{{ task.title }}</h3>
        {% if task.description %}
            <p>Description: {{ task.description }}</p>
        {% endif %}
        {% if task.completed == True %}
            <p>Status: Done</p>
        {% else %}
            <p>Status: In process</p>
        {% endif %}
        <div style="margin: 5px;">
            <a class="btn btn-secondary" href="{% url 'tasks:task_update' task.pk %}">Update Task</a>
            <a class="btn btn-danger" href="{% url 'tasks:task_delete' task.pk %}"><i class="bi bi-trash"></i></a>
        </div>
    </div>
{% endblock %}

templates/todos/task_list.html
{% extends "_base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">

    {% if group_id %}
        <a class="icon-link icon-link-hover link-body-emphasis" href="{% url 'groups:group_list' %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8"/>
            </svg>
            Back to Groups
        </a>

        <div class="d-flex justify-content-center align-items-center">
            <h3 class="d-inline m-1">{{ group.name }}</h3>
            <a href="{% url 'groups:group_update' group_id %}" class="link-body-emphasis"><i class="bi bi-pencil-square h3"></i></a>
        </div>

    {% else %}
        <h3>Tasks</h3>        
    {% endif %}

    <div class="task_list_container" style="overflow-y: auto; padding-bottom: 100px;">
    <ul>
        {% for task in incompleted_tasks %}
            <li>
                <input type="checkbox" class="task-checkbox" data-action-url="{% url 'tasks:toggle_task_completion' task.id %}">
                <a class="btn btn-light" href="{% url 'tasks:task_detail' task.pk %}" style="width: 250px;">{{ task.title }}</a>
            </li>
        {% endfor %}    
    </ul>

    {% if completed_tasks %}<hr>{% endif %}

    <ul>
        {% for task in completed_tasks %}
            <li>
                <input type="checkbox" class="task-checkbox" checked data-action-url="{% url 'tasks:toggle_task_completion' task.id %}">
                <a class="btn btn-light completed-task-btn" href="{% url 'tasks:task_detail' task.pk %}" style="width: 250px;">{{ task.title }}</a>
            </li>
        {% endfor %}
    </ul>
    </div>
    <div class="task-creation-form">
    {% if group_id %}
        <form method="post" action="{% url 'groups:group_task_list' group_id %}">
    {% else %}
        <form method="post" action="{% url 'tasks:task_list' %}">
    {% endif %}
        {% csrf_token %}
        <div class="d-flex justify-content-center align-items-center">
            {{ create_form.title }}
            <button class="btn btn-success task-add-btn" type="submit" style="margin: 5px;">ADD</button>
        </div>
    </form>
    </div>
    <script src="{% static 'js/main.js' %}"></script>

{% endblock content %}

templates/todos/task_update.html
{% extends "_base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="d-flex flex-column">
        <a class="icon-link icon-link-hover link-body-emphasis" href="{% url 'tasks:task_list' %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8"/>
            </svg>
            Back to Tasks
        </a>

        <h3>Edit Task</h3>
        <form method="post">{% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-success" type="submit">Save</button>
        </form>
    </div>
{% endblock %}