apis/urls.py
from django.urls import path
from .views import TaskListAPIView, TaskDetailAPIView, TaskGroupAPIView


urlpatterns = [
    path('groups/', TaskGroupAPIView.as_view(), name='group_list_api'),
    path('tasks/', TaskListAPIView.as_view(), name='task_list_api'),
    path('tasks/<uuid:pk>/', TaskDetailAPIView.as_view(), name='task_detail_api'),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path('not-admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('task/', include('todos.urls')),
    path('group/', include('groups.urls')),
    path('accounts/', include('allauth.urls')),
    path('custom_accounts/', include('accounts.urls')),
    path('api/', include('apis.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

groups/urls.py
from django.urls import path
from .views import (
    GroupListView, 
    GroupTaskListView, 
    GroupDeteleView, 
    GroupUpdateView,
    accept_invitation,
)

app_name = 'groups'

urlpatterns = [
    path('', GroupListView.as_view(), name='group_list'),
    path('<uuid:group_id>/tasks', GroupTaskListView.as_view(), name='group_task_list'),
    path('<uuid:group_id>/update', GroupUpdateView.as_view(), name='group_update'),
    path('<uuid:group_id>/delete', GroupDeteleView.as_view(), name='group_delete'),
    path('<uuid:token>/accept-invitation', accept_invitation, name='accept_invitation'),
]

groups/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User


class TaskGroup(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    members = models.ManyToManyField(User, through="Membership", related_name="task_groups")
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return self.name
    

class Membership(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    group = models.ForeignKey(TaskGroup, on_delete=models.CASCADE)


class Invitation(models.Model):
    email = models.EmailField()
    token = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    group = models.ForeignKey(TaskGroup, on_delete=models.CASCADE)
    sender = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    accepted = models.BooleanField(default=False)

groups/forms.py
from django import forms
from .models import TaskGroup


class CreateGroupForm(forms.ModelForm):
    name = forms.CharField(
        label='',
        required=True,
        widget=forms.TextInput(attrs={'placeholder': 'Add new group..'})
    )

    class Meta:
        model = TaskGroup
        fields = ['name']


class UpdateGroupForm(forms.ModelForm):
    class Meta:
        model = TaskGroup
        fields = ['name']

        

groups/views.py
from django.views.generic import ListView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.db import transaction

from todos.models import Task
from todos.mixins import TaskListViewMixin
from .models import TaskGroup, Invitation
from .forms import CreateGroupForm, UpdateGroupForm
from .utils import create_invitation, get_invitation_link


class GroupListView(LoginRequiredMixin, ListView):
    model = TaskGroup
    template_name = "groups/group_list.html"
    context_object_name = "groups"

    def get_queryset(self):
        return TaskGroup.objects.filter(members=self.request.user).order_by("-created_at")
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["create_form"] = CreateGroupForm()
        return context
    
    def post(self, request, *args, **kwargs):
        form = CreateGroupForm(request.POST)
        if form.is_valid():
            new_group = form.save(commit=False)
            with transaction.atomic():       
                new_group.save()
                new_group.members.add(request.user)
        return redirect("groups:group_list")

    
class GroupTaskListView(TaskListViewMixin, ListView):
    context_object_name = "group_tasks"

    def get_queryset(self):
        group_id = self.kwargs.get("group_id")
        group = get_object_or_404(TaskGroup, id=group_id)
        return Task.objects.filter(group=group)
    
    def post(self, request, *args, **kwargs):
        group_id = self.kwargs.get("group_id")
        form = self.form_class(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.user = request.user
            task.group = get_object_or_404(TaskGroup, id=group_id)
            task.save()

        task_ids = request.POST.getlist("task_ids")
        if task_ids:
            Task.objects.filter(id__in=task_ids, user=request.user).update(completed=True)
        
        return redirect(self.get_redirect_url())
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        group_id = self.kwargs.get("group_id")
        group = get_object_or_404(TaskGroup, id=group_id)
        context["create_form"] = self.form_class(initial={'group': group_id})
        context["group_id"] = group_id
        context["group"] = group
        return context
    
    def get_redirect_url(self):
        group_id = self.kwargs.get("group_id")
        return reverse("groups:group_task_list", args=[group_id])
    

class GroupUpdateView(LoginRequiredMixin, UpdateView):
    model = TaskGroup
    template_name = "groups/group_update.html"
    form_class = UpdateGroupForm
    success_url = "/group"

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)
    
    def get_object(self, queryset=None):
        group_id = self.kwargs.get('group_id')
        return get_object_or_404(TaskGroup, id=group_id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        group_id = self.kwargs.get('group_id')
        context['group_id'] = group_id

        invitation = create_invitation(self.request, group_id)
        invitation_link = get_invitation_link(self.request, invitation)
        context["invitation_link"] = invitation_link

        return context


class GroupDeteleView(LoginRequiredMixin, DeleteView):
    model = TaskGroup
    template_name = "groups/group_confirm_delete.html"
    success_url = reverse_lazy("groups:group_list")

    def get_object(self, queryset=None):
        group_id = self.kwargs.get('group_id')
        return get_object_or_404(TaskGroup, id=group_id)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        group_id = self.kwargs.get("group_id")
        group = get_object_or_404(TaskGroup, id=group_id)
        context['group_id'] = group_id
        context['group'] = group
        return context


def accept_invitation(request, token):
    if request.user.is_authenticated:
        invitation = get_object_or_404(Invitation, token=token)
        invitation.group.members.add(request.user)
        invitation.save()
        return redirect("groups:group_task_list", group_id=invitation.group.id)
    else:
        request.session["invitation_token"] = str(token)
        return redirect("account_login")
    

templates/groups/group_confirm_delete.html
{% extends "_base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="d-flex flex-column align-items-center text-center">
        <h3>Are you sure you wanna delete group '{{ group.name }}'?</h3> 
        <div class="d-flex">  
        <form method="post">{% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-danger mx-2" type="submit">Confirm</button>
        </form>

        <a class="btn btn-secondary " href="{% url 'groups:group_task_list' group_id %}">Back to Tasks</a>
    </div></div> 
{% endblock %}

templates/groups/group_list.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">

  <h3>Group List</h3>
  <div class="group_list_container" style="overflow-y: auto; padding-bottom: 100px;">
    <ul>
      {% for group in groups %}
        <li><a class="btn btn-light" href="{% url 'groups:group_task_list' group.id %}" style="width: 250px;">{{ group.name }}</a></li>
      {% endfor %}
    </ul>
  </div>
  
  <div class="group-creation-form">
    <form method="post" action="{% url 'groups:group_list' %}">{% csrf_token %}
      <div class="d-flex justify-content-center align-items-center">
          {{ create_form.name }}
          <button class="btn btn-success task-add-btn" type="submit" style="margin: 5px;">ADD</button>
      </div>
    </form>
  </div>
{% endblock %}

templates/groups/group_update.html
{% extends "_base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
    <div class="d-flex flex-column">
        <a class="icon-link icon-link-hover link-body-emphasis" href="{% url 'groups:group_task_list' group_id %}">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8"/>
            </svg>
            Back to Tasks
        </a>

        <h3>Edit Group</h3>
        <form method="post">{% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-success" type="submit">Save</button>
            <a class="btn btn-danger" href="{% url 'groups:group_delete' group_id %}">
                <i class="bi bi-trash"></i>
            </a>
        </form>
        
        {% if invitation_link %}
            <div style="margin-top: 30px;">
                <h5>You can share this group using the link:</h5>
                <button class="btn btn-secondary" onclick="copyLink()">Copy</button>
                <input type="text" value="{{ invitation_link }}" id="invitationLink" readonly>
                
            </div>
        {% endif %}
    </div>

    <script src="{% static 'js/main.js' %}"></script>
{% endblock %}