apis/urls.py
from django.urls import path
from .views import TaskListAPIView, TaskDetailAPIView, TaskGroupAPIView


urlpatterns = [
    path('groups/', TaskGroupAPIView.as_view(), name='group_list_api'),
    path('tasks/', TaskListAPIView.as_view(), name='task_list_api'),
    path('tasks/<uuid:pk>/', TaskDetailAPIView.as_view(), name='task_detail_api'),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path('not-admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('task/', include('todos.urls')),
    path('group/', include('groups.urls')),
    path('accounts/', include('allauth.urls')),
    path('custom_accounts/', include('accounts.urls')),
    path('api/', include('apis.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

groups/urls.py
from django.urls import path
from .views import (
    GroupListView, 
    GroupTaskListView, 
    GroupDeteleView, 
    GroupUpdateView,
    accept_invitation,
)

app_name = 'groups'

urlpatterns = [
    path('', GroupListView.as_view(), name='group_list'),
    path('<uuid:group_id>/tasks', GroupTaskListView.as_view(), name='group_task_list'),
    path('<uuid:group_id>/update', GroupUpdateView.as_view(), name='group_update'),
    path('<uuid:group_id>/delete', GroupDeteleView.as_view(), name='group_delete'),
    path('<uuid:token>/accept-invitation', accept_invitation, name='accept_invitation'),
]

todos/urls.py
from django.urls import path

from .views import (
    TaskListView,
    TaskDetailView,
    TaskUpdateView,
    TaskDeleteView,
    ToggleTaskCompletionView,
)

app_name = "tasks"

urlpatterns = [
    path('', TaskListView.as_view(), name='task_list'),
    path('<uuid:pk>/', TaskDetailView.as_view(), name='task_detail'),
    path('<uuid:pk>/update', TaskUpdateView.as_view(), name='task_update'),
    path('<uuid:pk>/detele', TaskDeleteView.as_view(), name='task_delete'),
    path('toggle-completion/<uuid:task_id>/', ToggleTaskCompletionView.as_view(), name='toggle_task_completion'),
]

templates/_base.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="light">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <title>{% block title %}TODO{% endblock title %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <div>
            <a class="navbar-brand" href="{% url 'home' %}">TODO APP</a>
            <button id="theme-toggle"></button>
          </div>
          
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-center" id="navbarNavDropdown">
            <ul class="navbar-nav d-flex justify-content-center align-items-center">
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">About</a>
              </li>

              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'tasks:task_list' %}">Tasks</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'groups:group_list' %}">Groups</a>
              </li>
              <div class="dropdown mx-auto">
                <a class="btn btn-light dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  {{ user.username }}
                </a>
                <ul class="dropdown-menu">
                  <li class="text-center"><a class="dropdown-item" href="{% url 'change_password' %}">Change Password</a></li>
                  <li class="text-center"><a class="dropdown-item" href="{% url 'account_logout' %}">Logout</a></li>
                </ul>
              </div>

              {% else %}
              <li class="nav-item m-1">
                <a class="btn btn-success" href="{% url 'account_login' %}">Login</a>
              </li>
              <li class="nav-item m-1">
                <a class="btn btn-primary" href="{% url 'account_signup' %}">Signup</a>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>

    <div class="d-flex flex-column justify-content-center align-items-center">
        {% block content %}
        {% endblock %}
    </div>

    <script src="{% static 'js/main.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

templates/about.html
{% extends "_base.html" %}

{% block title %}TODO APP{% endblock title %}

{% block content %}
    <h1>About page</h1>
    <div class="text-container">
        <p>Hello, I'm Paul. I'm young student and I have a very active lifestyle) 
        So for me organizing and planning are very important things. 
        Currently, I'm learning Django and this is my project, that I hope will help other people too) 
        I'm passionate about codding and eager to expand my skills in web development.</p>
        
        {% if user.is_authenticated %}
            <p>Feel free to connect with me on social media:</p>
            <div class="d-flex justify-content-around">
                <a class="link-body-emphasis" href="https://www.instagram.com/koval1off/" target="_blank"><i class="bi bi-instagram"></i></a>
                <a class="link-body-emphasis" href="https://t.me/koval1off" target="_blank"><i class="bi bi-telegram"></i></a>
                <a class="link-body-emphasis" href="https://www.linkedin.com/in/paul-kovaliov-060805237/" target="_blank"><i class="bi bi-linkedin"></i></a>
                <a class="link-body-emphasis" href="https://twitter.com/Paul77361437" target="_blank"><i class="bi bi-twitter-x"></i></a>
                <a class="link-body-emphasis" href="mailto:kovaliov043@gmail.com" target="_blank"><i class="bi bi-envelope-fill"></i></a>
            </div>
        {% endif %}
    </div>
{% endblock content %}

templates/home.html
{% extends "_base.html" %}

{% block title %}TODO APP{% endblock title %}

{% block content %}
    <h1>Welcome to TODO APP!</h1>
    <div class="text-container">
        {% if user.is_authenticated %}
            <div>
                <p>Hello dear {{ user.username }}! We hope this app will help you to organize your life better!</p>
            </div>
        {% else %}
            <h5>Please Login or SignUp to see more features!</h5>
        {% endif %}
    </div>
{% endblock content %}

templates/task_form.html
{% extends "_base.html" %}

{% block content %}

    <h1>Task Form</h1>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>

    <a href="{% url 'tasks:task_list' %}">Back to Tasks</a>

{% endblock %}

templates/task_list.html
{% extends "_base.html" %}

{% block content %}

    <h1>List of Tasks</h1>
    <ul>
        {% for task in tasks %}
            <li>
                <a href="{% url 'tasks:task_detail' task.pk %}">{{ task.title }}</a>
                {% if task.is_completed %}(Done){% endif %}
            </li>    
        {% endfor %} 
    </ul>

    <h2>Add new Task</h2>
    <form method="post" action="{% url 'tasks:task_list' %}">{% csrf_token %}
        {{ create_form.as_p }}
        <button type="submit">ADD</button>
    </form>

{% endblock content %}